### ISSUE TITLE
Error while training mill 19 building, centroid 0 in a distributed fashion 

### ISSUE THREAD

**Issue by madratman** [cmusatyalab/mega-nerf#11]
I get this error after a while trying to train (on multiple nodes with multiple gpus each) a model on the building dataset, for chunk/submodule 0 (using the provided cluster masks)
Any tips on debugging this? 
Seems like somewhere there is an issue in a sample. 
```
 28%|██▊       | 140533/500000 [15:32:21<45:35:06,  2.19it/s]
 28%|██▊       | 140534/500000 [15:32:22<50:19:14,  1.98it/s]
 28%|██▊       | 140535/500000 [15:32:23<53:45:04,  1.86it/s]
 28%|██▊       | 140536/500000 [15:32:23<44:03:00,  2.27it/s]
 28%|██▊       | 140537/500000 [15:32:23<49:43:21,  2.01it/s]
 28%|██▊       | 140538/500000 [15:32:24<55:23:35,  1.80it/s]
 28%|██▊       | 140539/500000 [15:32:24<46:40:38,  2.14it/s]
 28%|██▊       | 140540/500000 [15:32:25<46:16:18,  2.16it/s]
 28%|██▊       | 140541/500000 [15:32:25<38:48:16,  2.57it/s]
 28%|██▊       | 140542/500000 [15:32:25<34:51:35,  2.86it/s]
 28%|██▊       | 140543/500000 [15:32:26<38:54:21,  2.57it/s]
 28%|██▊       | 140544/500000 [15:32:26<46:17:54,  2.16it/s]
 28%|██▊       | 140545/500000 [15:32:27<40:27:56,  2.47it/s]
 28%|██▊       | 140546/500000 [15:32:27<46:56:04,  2.13it/s]
 28%|██▊       | 140547/500000 [15:32:28<52:37:22,  1.90it/s]ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
[stderr]  "message": {
[stderr]    "message": "ValueError: cannot reshape array of size 42028165 into shape (42107792,)",
[stderr]    "extraInfo": {
[stderr]      "py_callstack": "Traceback (most recent call last):\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/tmp/code/mega_nerf/train.py\", line 24, in main\n    Runner(hparams).train()\n  File \"/tmp/code/mega_nerf/runner.py\", line 226, in train\n    dataset.load_chunk()\n  File \"/tmp/code/mega_nerf/datasets/filesystem_dataset.py\", line 80, in load_chunk\n    chosen, self._loaded_rgbs, self._loaded_rays, self._loaded_image_indices = self._chunk_future.result()\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/_base.py\", line 438, in result\n    return self.__get_result()\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/_base.py\", line 390, in __get_result\n    raise self._exception\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/tmp/code/mega_nerf/datasets/filesystem_dataset.py\", line 111, in _load_chunk_inner\n    loaded_pixel_indices = torch.IntTensor(np.load(self._ray_arrays[next_index]))\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/numpy/lib/npyio.py\", line 440, in load\n    return format.read_array(fid, allow_pickle=allow_pickle,\n  File \"/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/numpy/lib/format.py\", line 787, in read_array\n    array.shape = shape\nValueError: cannot reshape array of size 42028165 into shape (42107792,)\n",
[stderr]      "timestamp": "1651655215"
[stderr]    }
[stderr]  }
[stderr]}
[stderr]Traceback (most recent call last):
[stderr]  File "/tmp/code/mega_nerf/train.py", line 28, in <module>
[stderr]    main(_get_train_opts())
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
[stderr]    return f(*args, **kwargs)
[stderr]  File "/tmp/code/mega_nerf/train.py", line 24, in main
[stderr]    Runner(hparams).train()
[stderr]  File "/tmp/code/mega_nerf/runner.py", line 226, in train
[stderr]    dataset.load_chunk()
[stderr]  File "/tmp/code/mega_nerf/datasets/filesystem_dataset.py", line 80, in load_chunk
[stderr]    chosen, self._loaded_rgbs, self._loaded_rays, self._loaded_image_indices = self._chunk_future.result()
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/_base.py", line 438, in result
[stderr]    return self.__get_result()
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
[stderr]    raise self._exception
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/concurrent/futures/thread.py", line 52, in run
[stderr]    result = self.fn(*self.args, **self.kwargs)
[stderr]  File "/tmp/code/mega_nerf/datasets/filesystem_dataset.py", line 111, in _load_chunk_inner
[stderr]    loaded_pixel_indices = torch.IntTensor(np.load(self._ray_arrays[next_index]))
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/numpy/lib/npyio.py", line 440, in load
[stderr]    return format.read_array(fid, allow_pickle=allow_pickle,
[stderr]  File "/azureml-envs/azureml_42fe9568fca52a4c68567983a86d6e0f/lib/python3.9/site-packages/numpy/lib/format.py", line 787, in read_array
[stderr]    array.shape = shape
[stderr]ValueError: cannot reshape array of size 42028165 into shape (42107792,)
```

**Comment by hturki** [comment]
I've seen this happen when the ```chunk_paths``` directory runs out of disk space. Can you confirm if that's the case?

**Comment by ZZy129326999** [comment]
> chunk

Hello, how exactly is the chunk file generated?

**Comment by hturki** [comment]
see https://github.com/cmusatyalab/mega-nerf/issues/1#issuecomment-1079388085
