### ISSUE TITLE
when I run code on my own data, it gets wrong

### ISSUE THREAD

**Issue by menglongyue** [cmusatyalab/mega-nerf#16]
thanks for your excellent work. when I run the code on my own data, it gets wrong, but I do not know why? 

Namespace(config_file='configs/mega-nerf/deyang.yaml', dataset_type='filesystem', chunk_paths=['/data1/huangqj/deyang_chunk/0'], num_chunks=200, disk_flush_size=10000000, train_every=1, cluster_mask_path='/data1/huangqj/deyang_cluster/0', ckpt_path=None, container_path=None, near=1, far=None, ray_altitude_range=[8.0, 140.0], coarse_samples=256, fine_samples=512, train_scale_factor=1, val_scale_factor=4, pos_xyz_dim=12, pos_dir_dim=4, layers=8, skip_layers=[4], layer_dim=256, bg_layer_dim=256, appearance_dim=48, affine_appearance=False, use_cascade=False, train_mega_nerf=None, boundary_margin=1.15, all_val=False, cluster_2d=False, sh_deg=None, center_pixels=True, shifted_softplus=True, batch_size=1024, image_pixel_batch_size=65536, model_chunk_size=32768, perturb=1.0, noise_std=1.0, lr=0.0005, lr_decay_factor=0.1, bg_nerf=True, ellipse_scale_factor=1.1, ellipse_bounds=True, train_iterations=300000, val_interval=500001, ckpt_interval=10000, resume_ckpt_state=True, amp=True, detect_anomalies=False, random_seed=42, exp_name='deyang0', dataset_path='/data1/huangqj/deyang_new')
Origin: tensor([ 0.0065, -0.0613,  0.0219]), scale factor: 225.0
Ray bounds: 0.0044444444444444444, 100000.0
Ray altitude range in [-1, 1] space: [tensor(0.0355), tensor(0.6222)]
Ray altitude range in metric space: [8.0, 140.0]
Using cluster mask path: /data1/huangqj/deyang_cluster/0
Using cluster mask path: /data1/huangqj/deyang_cluster/0
Using 86 train images and 6 val images
Camera range in metric space: tensor([-2.8855, -3.5477, -3.9225]) tensor([2.8984, 3.4252, 3.9663])
Camera range in [-1, 1] space: tensor([-0.0129, -0.0155, -0.0175]) tensor([0.0129, 0.0155, 0.0175])
Camera range in [-1, 1] space with ray altitude range: tensor([-0.0129, -0.0155, -0.0175]) tensor([0.6222, 0.0155, 0.0175])
Sphere center: tensor([0.3047, 0.0000, 0.0000], device='cuda:0'), radius: tensor([0.5841, 0.0285, 0.0322], device='cuda:0')
All intrinsics identical: W: 6000 H: 4000, intrinsics: tensor([5264.3481, 5264.3481, 3000.0000, 2000.0000])
Allocating 200 chunks to dataset path /data1/huangqj/deyang_chunk/0
200 chunks allocated
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 86/86 [05:05<00:00,  3.55s/it]
Finished writing chunks to dataset paths
  0%|                                                                                                                                                    | 124/300000 [02:35<94:05:37,  1.13s/it]
{
  "message": {
    "message": "Exception: Train metrics not finite: {'psnr': nan, 'depth_variance': tensor(nan, device='cuda:0'), 'photo_loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>), 'loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)}",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/data1/huangqj/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/huangqj/mega_nerf_ori/mega_nerf/train.py\", line 25, in main\n    Runner(hparams).train()\n  File \"/home/huangqj/mega_nerf_ori/mega_nerf/runner.py\", line 261, in train\n    raise Exception('Train metrics not finite: {}'.format(metrics))\nException: Train metrics not finite: {'psnr': nan, 'depth_variance': tensor(nan, device='cuda:0'), 'photo_loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>), 'loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)}\n",
      "timestamp": "1655556971"
    }
  }
}
Traceback (most recent call last):
  File "/home/huangqj/mega_nerf_ori/mega_nerf/train.py", line 29, in <module>
    main(_get_train_opts())
  File "/data1/huangqj/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/huangqj/mega_nerf_ori/mega_nerf/train.py", line 25, in main
    Runner(hparams).train()
  File "/home/huangqj/mega_nerf_ori/mega_nerf/runner.py", line 261, in train
    raise Exception('Train metrics not finite: {}'.format(metrics))
Exception: Train metrics not finite: {'psnr': nan, 'depth_variance': tensor(nan, device='cuda:0'), 'photo_loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>), 'loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)}
  0%|                                                                                                                                                   | 124/300000 [02:35<104:46:26,  1.26s/it]

**Comment by hturki** [comment]
It's hard to say without looking at your data, my recommendation would be to sanity check that results look sensible at small scale, ie: train the scene using a single NeRF for 10k iterations or so. Do the results look sensible then? If not then there is likely something wrong with your poses / ray bounds / etc

**Comment by menglongyue** [comment]
I changed my dataset to a bigger one, which has 507 images, and the resolution is 6000x4000. the altitude of these images is below 160， and I set the scale parameter in clomp_to_mega_nerf.py to 200（I do not know how to get scale parameter, so I set it to 200 following building dataset）. all poses are computed by colmap, and not refined by pixsfm. I have tried to set grid to 1x1 and 2x4，training results are the same as I mentioned bofore. all outputs turned to "None", such as loss,  psnr, and so on. could you please give me some advice?

**Comment by ZZy129326999** [comment]
Hello, I saw your question in MegaNeRF, you seem to have made 200 chunks, I would like to know how you generate chunk files, thank you very much!--chunk_paths $SCRATCH_PATH

**Comment by ZZy129326999** [comment]
I have solved it, it is directly set but not created to finish it.

> Hello, I saw your question in MegaNeRF, you seem to have made 200 chunks, I would like to know how you generate chunk files, thank you very much!--chunk_paths $SCRATCH_PATH
I have solved it, it is directly set but not created to finish it. Thank your this message!

**Comment by hturki** [comment]
@menglongyue  - if you think that altitude is the issue, you can disable it the altitude truncation altogether by specifying the no_ellipse_bounds option

**Comment by sumanttyagi** [comment]
@menglongyue 1. did you merge the colmap poses , as in my case 3 models are being generated by the colmap ? how should i take this forward ? 
2. did you use model aligner on colmap ?

even i am facing similar @hturki  https://github.com/cmusatyalab/mega-nerf/issues/35

**Comment by sumanttyagi** [comment]
> @menglongyue - if you think that altitude is the issue, you can disable it the altitude truncation altogether by specifying the no_ellipse_bounds option

i tired by changing no_ellipse_bounds = False.Keeping false as default in opts.py  
still facing the same error .

**Comment by QasimBinSaeed1** [comment]
@ZZy129326999 Could you kindly guide me on how to obtain the chunk_path here?
