### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by sjtuytc** [cmusatyalab/mega-nerf#30]
Hi, when I run the eval command via: 
`python mega_nerf/eval.py --config_file configs/nerf/building.yaml --exp_name exp_official --dataset_path ./data/building/building-pixsfm --container_path ./data/building/building-pixsfm-8.pt`
I face the following error:
`Traceback (most recent call last):
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/eval.py", line 30, in <module>
    main(_get_eval_opts())
  File "/mnt/backup2/home/zlzhao21/software/miniconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/eval.py", line 26, in main
    Runner(hparams).eval()
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/runner.py", line 309, in eval
    val_metrics = self._run_validation(0)
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/runner.py", line 409, in _run_validation
    results, _ = self.render_image(metadata_item)
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/runner.py", line 569, in render_image
    result_batch, _ = render_rays(nerf=nerf, bg_nerf=bg_nerf,
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/rendering.py", line 88, in render_rays
    results = _get_results(nerf=nerf,
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/rendering.py", line 195, in _get_results
    _inference(results=results,
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/rendering.py", line 324, in _inference
    model_chunk = nerf(typ == 'coarse', xyz_chunk, sigma_noise=sigma_noise)
  File "/mnt/backup2/home/zlzhao21/software/miniconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/backup2/home/zlzhao21/aug_code/mega-nerf/mega_nerf/models/mega_nerf.py", line 22, in forward
    cluster_distances = torch.cdist(x[:, self.cluster_dim_start:3], self.centroids[:, self.cluster_dim_start:])
TypeError: 'bool' object is not subscriptable`

How can I deal with this?

**Comment by sjtuytc** [comment]
The reason is to switch from nerf config to meta-nerf config.

**Comment by ChristmasLatte** [comment]
> The reason is to switch from nerf config to meta-nerf config.

Nice, that's works for me

**Comment by ghd98522** [comment]
I had the same problem, how did you solve it?

**Comment by IaroslavS** [comment]
> The reason is to switch from nerf config to meta-nerf config.

What is the meta-config ? Where is it located ?

**Comment by Jixuan-Fan** [comment]
Change `nerf` to `mega-nerf` is not enough for me, the following line should be changed to `model_chunk = nerf(xyz_chunk, typ == 'coarse', sigma_noise=sigma_noise)`
https://github.com/cmusatyalab/mega-nerf/blob/76d8d76b66d70f8a0819defc0cef4fb9aa251672/mega_nerf/rendering.py#L324
