### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by jingfengguo-ai** [cmusatyalab/mega-nerf#72]
Traceback (most recent call last):
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/eval.py", line 30, in <module>
    main(_get_eval_opts())
  File "/share/home/drliuqi/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/eval.py", line 26, in main
    Runner(hparams).eval()
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/runner.py", line 323, in eval
    val_metrics = self._run_validation(0)
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/runner.py", line 427, in _run_validation
    results, _ = self.render_image(metadata_item)
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/runner.py", line 587, in render_image
    result_batch, _ = render_rays(nerf=nerf, bg_nerf=bg_nerf,
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/rendering.py", line 88, in render_rays
    results = _get_results(nerf=nerf,
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/rendering.py", line 195, in _get_results
    _inference(results=results,
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/rendering.py", line 324, in _inference
    model_chunk = nerf(typ == 'coarse', xyz_chunk, sigma_noise=sigma_noise)
  File "/share/home/drliuqi/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/drliuqi/gjf/3D-Reconstruction/mega-nerf-main/mega_nerf/models/mega_nerf.py", line 22, in forward
    cluster_distances = torch.cdist(x[:, self.cluster_dim_start:3], self.centroids[:, self.cluster_dim_start:])
TypeError: 'bool' object is not subscriptable
can you help me？thanks！

**Comment by ghd98522** [comment]
I'm having the same issue, did you fix it?

**Comment by jingfengguo-ai** [comment]
> I'm having the same issue, did you fix it?

no，do you have any idea?

**Comment by ghd98522** [comment]
This problem has been bothering me for a long time, and I can't solve it either


 ***@***.***
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  08/22/2023 15:32 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [cmusatyalab/mega-nerf] Evaluation Error (Issue #72)  

I'm having the same issue, did you fix it?
no，do you have any idea?

**Comment by A-pril** [comment]
> This problem has been bothering me for a long time, and I can't solve it either ***@***.*** ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 08/22/2023 15:32 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [cmusatyalab/mega-nerf] Evaluation Error (Issue #72) I'm having the same issue, did you fix it? no，do you have any idea? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

[This answer](https://github.com/cmusatyalab/mega-nerf/issues/30#issuecomment-1207207347) maybe help you, just fix the config's setting

**Comment by jingfengguo-ai** [comment]
> > This problem has been bothering me for a long time, and I can't solve it either _**@**_.*** _**@**_.***
> > […](#)
> > ---- Replied Message ---- From _**@**_._**> Date 08/22/2023 15:32 To _**@**_.**_> Cc _**@**_._**>**_@_**.**_> Subject Re: [cmusatyalab/mega-nerf] Evaluation Error (Issue #72) I'm having the same issue, did you fix it? no，do you have any idea? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> [This answer](https://github.com/cmusatyalab/mega-nerf/issues/30#issuecomment-1207207347) maybe help you, just fix the config's setting

Thank you very much! It works for me.
I have another problem, when I try to train mega-nerf on my own dataset, it gives error：
Exception: Train metrics not finite: {'psnr': nan, 'depth_variance': tensor(nan, device='cuda:0'), 'photo_loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>), 'loss': tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)}
do you have any idea?
