### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'exists'

### ISSUE THREAD

**Issue by SSXXSSXX** [cmusatyalab/mega-nerf#87]
I have generated training partitions for each submodule and am now ready to train each submodule. My training command is as follows:
Python mega nerf/train. py -- config_file configs/mega nerf/quad. yaml -- expname exp1-- dataset_path CAMERA-POSE/quad pixsfm -- chunk_paths log1-- cluster_mask_path output/0
The following issues were encountered while running the command:

Traceback (most recent call last):
  File "/home/ss/mega-nerf-main/mega_nerf/train.py", line 28, in <module>
    main(_get_train_opts())
  File "/home/ss/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/ss/mega-nerf-main/mega_nerf/train.py", line 24, in main
    Runner(hparams).train()
  File "/home/ss/mega-nerf-main/mega_nerf/runner.py", line 107, in __init__
    self.train_items, self.val_items = self._get_image_metadata()
  File "/home/ss/mega-nerf-main/mega_nerf/runner.py", line 628, in _get_image_metadata
    train_items = [
  File "/home/ss/mega-nerf-main/mega_nerf/runner.py", line 629, in <listcomp>
    self._get_metadata_item(x, image_indices[x.name], self.hparams.train_scale_factor, x in val_paths_set) for x
  File "/home/ss/mega-nerf-main/mega_nerf/runner.py", line 645, in _get_metadata_item
    assert image_path.exists()
AttributeError: 'NoneType' object has no attribute 'exists'

![error](https://github.com/cmusatyalab/mega-nerf/assets/75832534/ee7a93f4-5275-419e-9786-cb915e5e3fd1)

**Comment by Shrinkink** [comment]
您好，我想问一下您的这个问题解决了吗，我也遇到了同样的问题
